import{a as q,S as v,i}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const E="https://pixabay.com/api/",B="53601534-4242f4726582a914ce6310b57";async function m(r,o){const n={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await q.get(E,{params:n})).data}const g=document.querySelector(".gallery"),f=document.querySelector(".loader-wrapper"),p=document.querySelector(".load-more-btn"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const o=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:a,comments:b,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${n}" alt="${e}" />
        </a>
        <ul class="info">
          <li><span>Likes</span>${t}</li>
          <li><span>Views</span>${a}</li>
          <li><span>Comments</span>${b}</li>
          <li><span>Downloads</span>${S}</li>
        </ul>
      </li>`).join("");g.insertAdjacentHTML("beforeend",o),M.refresh()}function P(){g.innerHTML=""}function y(){f.classList.remove("is-hidden")}function l(){f.classList.add("is-hidden")}function L(){p.classList.remove("is-hidden")}function d(){p.classList.add("is-hidden")}const $=document.querySelector(".form"),R=document.querySelector(".load-more-btn");let c="",u=1,w=0;$.addEventListener("submit",O);R.addEventListener("click",T);async function O(r){r.preventDefault();const o=r.currentTarget;if(c=o.elements["search-text"].value.trim(),!c){i.warning({message:"Please enter a search term!",position:"topRight"});return}u=1,P(),d(),y();try{const n=await m(c,u);if(l(),w=n.totalHits,!n.hits.length){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(n.hits),n.hits.length===15&&L()}catch{i.error({message:"Error loading images. Try again later!",position:"topRight"})}finally{l(),o.reset()}}async function T(){u+=1,y(),d();try{const r=await m(c,u);if(l(),h(r.hits),x(),document.querySelectorAll(".gallery-item").length>=w){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d();return}L()}catch{l(),i.error({message:"Error loading images. Try again later!",position:"topRight"})}finally{l()}}function x(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
