import{a as v,S as E,i}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",M="53601534-4242f4726582a914ce6310b57";async function m(o,t){const a={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await v.get(B,{params:a})).data}const f=document.querySelector(".gallery"),g=document.querySelector(".loader-wrapper"),y=document.querySelector(".load-more-btn"),P=new E(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
        <ul class="info">
          <li><span>Likes</span>${r}</li>
          <li><span>Views</span>${n}</li>
          <li><span>Comments</span>${S}</li>
          <li><span>Downloads</span>${q}</li>
        </ul>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){f.innerHTML=""}function p(){g.classList.remove("is-hidden")}function c(){g.classList.add("is-hidden")}function L(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const w=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let l="",u=1,b=0;w.addEventListener("submit",x);O.addEventListener("click",A);async function x(o){if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){i.warning({message:"Please enter a search term!"});return}u=1,$(),d(),p();try{const t=await m(l,u);if(c(),b=t.totalHits,!t.hits.length){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),t.hits.length===15&&L()}catch{c(),i.error({message:"Error loading images. Try again later!"})}w.reset()}async function A(){u+=1,p(),d();try{const o=await m(l,u);if(c(),h(o.hits),I(),document.querySelectorAll(".gallery-item").length>=b){i.info({message:"We're sorry, but you've reached the end of search results."}),d();return}L()}catch{c(),i.error({message:"Error loading images. Try again later!"})}}function I(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
